---
title: "Load Data"
author: "Satrio Wiradika (300578313)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Sources, Licenses, and Summary of the Data

## Crash Analysis System (CAS) Data: casdata

* Source: https://opendata-nzta.opendata.arcgis.com/datasets/NZTA::crash-analysis-system-cas-data-1/about
* License: [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0)
* Summary of the data:

```{r, include = FALSE}
library(pander)
```

```{r, echo = FALSE}
casdata = read.csv("../../Datasets/Crash_Analysis_System_(CAS)_data.csv")

casdata$crashDirectionDescription = factor(casdata$crashDirectionDescription, exclude = 'Null')
casdata$crashSeverity = factor(casdata$crashSeverity, levels=c('N','M', 'S', 'F'))
casdata$crashSHDescription = as.logical(casdata$crashSHDescription)
casdata$directionRoleDescription = as.factor(casdata$directionRoleDescription)
casdata$flatHill = factor(casdata$flatHill, exclude = "Null")
casdata$holiday = as.factor(casdata$holiday)
casdata$light = as.factor(casdata$light)
casdata$region = factor(casdata$region, exclude = "")
casdata$roadCharacter[casdata$roadCharacter == "Null"] = ''
casdata$roadCharacter = as.factor(casdata$roadCharacter)
casdata$roadLane = as.factor(casdata$roadLane)
casdata$roadSurface = factor(casdata$roadSurface, exclude = "Null")
casdata$streetLight[casdata$streetLight == "Null"] = "Unknown"
casdata$streetLight = as.factor(casdata$streetLight)
casdata$trafficControl = as.factor(casdata$trafficControl)
casdata$urban = as.factor(casdata$urban)
casdata$weatherA[casdata$weatherA == "Null"] = "Unknown"
casdata$weatherA = as.factor(casdata$weatherA)
casdata$weatherB[casdata$weatherB == "Null" | casdata$weatherB == "None"] = "Unknown"
casdata$weatherB = as.factor(casdata$weatherB)

casdata = subset(casdata, select=-c(crashRoadSideRoad, intersection))

pander(summary(casdata))
```

# Field Description of Data

## Crash Analysis System (CAS) Data: casdata_fd

```{r, include = FALSE}
library(dplyr)
```

```{r, echo = FALSE}
variable_list <- list(
  advisorySpeed = "The advisory (adv) speed (spd) at the crash site at the time of the crash.",
  areaUnitID = "The unique identifier of an area unit.",
  bicycle = "Derived variable to indicate how many bicycles were involved in the crash.",
  bridge = "Derived variable to indicate how many times a bridge, tunnel, the abutments, handrails were struck in the crash.",
  bus = "Derived variable to indicate how many buses were involved in the crash (excluding school buses which are counted in the SCHOOL_BUS field).",
  carStationWagon = "Derived variable to indicate how many cars or station wagons were involved in the crash.",
  cliffBank = "Derived variable to indicate how many times a 'cliff' or 'bank' was struck in the crash. This includes retaining walls.",
  crashDirectionDescription = "The direction (dirn) of the crash from the reference point. Values possible are 'North', 'East', 'South' or 'West'.",
  crashDistance = "The distance (dist) of the crash from the reference point for the crash. The reference point is often the intersection of 'crash road' and 'side road' (refer to 'cr_rd_sd_rd' variable).",
  crashFinancialYear = "The financial (fin) year in which a crash occurred, if known. This is displayed as a string field. eg 2004/2005.",
  crashLocation1 = "Part 1 of the 'crash location' (crash_locn). May be a road name, route position (RP), landmark, or other, e.g. 'Ninety Mile Beach'. Used for location descriptions in reports etc.",
  crashLocation2 = "Part 2 of the 'crash location' (crash_locn). May be a side road name, landmark etc. Used for location descriptions in reports etc.",
  crashSeverity = "The severity of a crash. Possible values are 'F' (fatal), 'S' (serious), 'M' (minor), 'N' (non-injury). This is determined by the worst injury sustained in the crash at time of entry.",
  crashSHDescription = "Indicates where a crash is reported to have occurred on a State Highway (SH) marked ‘1’, or on another road type marked ‘2’.",
  crashYear = "The year in which a crash occurred, if known.",
  debris = "Derived variable to indicate how many times debris, boulders or items dropped or thrown from a vehicle(s) were struck in the crash.",
  directionRoleDescription = "The direction (dirn) of the principal vehicle involved in the crash. Possible values are North, South, East or West.",
  ditch = "Derived variable to indicate how many times a 'ditch' or 'waterable drainage channel' was struck in a crash.",
  easting = "The easting coordinate of an object (usually a crash) expressed in NZMG referred to the WGS84 datum to a precision of 1m. Please note, in some instances crashes are not able to be assigned to GPS co-ordinates. These crashes have been assigned eastings and northings of ‘0,0’ in this dataset. There are two main reasons that a GPS coordinate cannot be allocated to a crash. Firstly, that the crash has been reported but the location was unknown. Secondly in a small number of instances, a crash may have occurred on a road which is not yet captured on the CAS spatial layer.",
  fatalCount = "A count of the number of fatal casualties associated with this crash.",
  fence = "Derived variable to indicate how many times a 'fence' was struck in the crash. This includes letterbox(es), hoardings, private roadside furniture, hedges, sight rails, etc.",
  flatHill = "Whether the road is flat or sloped. Possible values include 'Flat or 'Hill'.",
  guardRail = "Derived variable to indicate how many times a guard or guard rail was struck in the crash. This includes 'New Jersey' barriers, 'ARMCO', sand filled barriers, wire catch fences, etc.",
  holiday = "Indicates where a crash occurred during a 'Christmas/New Year', 'Easter', 'Queens Birthday' or 'Labour Weekend' holiday period, otherwise 'None'.",
  houseOrBuilding = "Derived variable to indicate how many times a houses, garages, sheds or other buildings(Bldg) were struck in the crash.",
  intersectionMidblock = "A derived variable to indicate if a crash occurred at an intersection (intsn) or not. The 'intsn_midblock' variable is calculated using the 'intersection' and 'junction_type' variables. Values are 'Intersection' (where intersection variable = 'Intersection' or {'Intersection' = 'At Landmark' and junction_type is not in ('Unknown' or 'Driveway')} OR {Intersection = 'Unknown' and crash_dist <= 10}), otherwise 'Midblock' for crashes not meeting the criteria for 'Intersection').",
  kerb = "Derived variable to indicate how many times a kerb was struck in the crash, that contributed directly to the crash.",
  light = "The light at the time and place of the crash. Possible values: 'Bright Sun', 'Overcast', 'Twilight', 'Dark' or 'Unknown'.",
  meshblockId = "The unique identifier of a meshblock.",
  minorInjuryCount = "A count of the number of minor injuries (inj) associated with this crash.",
  moped = "Derived variable to indicate how many mopeds were involved in the crash.",
  motorcycle = "Derived variable to indicate how many motorcycles were involved in the crash.",
  northing = "The northing coordinate of an object (usually a crash) expressed in NZMG referred to the WGS84 datum to a precision of 1m. Please note, in some instances crashes are not able to be assigned to GPS co-ordinates. These crashes have been assigned eastings and northings of ‘0,0’ in this dataset. There are two main reasons that a GPS coordinate cannot be allocated to a crash. Firstly, that the crash has been reported but the location was unknown. Secondly in a small number of instances, a crash may have occurred on a road which is not yet captured on the CAS spatial layer.",
  NumberOfLanes = "The number(num) of lanes on the crash road.",
  objectThrownOrDropped = "Derived variable to indicate how many times objects were thrown at or dropped on vehicles in the crash.",
  otherObject = "Derived variable to indicate how many times an object was struck in a crash and the object struck was not pre-defined. This variable includes stockpiled materials, rubbish bins, fallen poles, fallen trees, etc.",
  otherVehicleType = "Derived variable to indicate how many other vehicles (not included in any other category) were involved in the crash.",
  overBank = "Derived variable to indicate how many times an embankment was struck or driven over during a crash. This variable includes other vertical drops driven over during a crash.",
  parkedVehicle = "Derived variable to indicate how many times a parked or unattended vehicle was struck in the crash. This variable can include trailers.",
  phoneBoxEtc = "Derived variable to indicate how many times a telephone kiosk traffic signal controllers, bus shelters or other public furniture was struck in the crash.",
  pedestrian = "Derived variable to indicate how many pedestrians were involved in the crash. This includes pedestrians on skateboards, scooters and wheelchairs.",
  postOrPole = "Derived variable to indicate how many times a post or pole was struck in the crash. This includes light, power, phone, utility poles and objects practically forming part of a pole (i.e. 'Transformer Guy' wires).",
  region = "Identifies the local government (LG) region. The boundaries match territorial local authority (TLA) boundaries.",
  roadCharacter = "The general nature of the road. Possible values include 'Bridge', 'Motorway Ramp', ‘Rail crossing’ or 'Nil'.",
  roadLane = "The lane configuration of the road. Possible values : '1' (one way), '2' (two way), 'M' (for where a median exists), 'O' (for off-road lane configurations), ' ' (for unknown or invalid configurations).",
  roadMarkings = "The road markings at the crash site. Possible values: 'Ped Crossing' (for pedestrian crossings), 'Raised Island', 'Painted Island', 'No Passing Lanes', 'Centre Line', 'No Marks' or 'Unknown'.",
  roadSurface = "The road surface description applying at the crash site. Possible values: 'Sealed' or 'Unsealed'.",
  roadworks = "Derived variable to indicate how many times an object associated with 'roadworks' (including signs, cones, drums, barriers, but not roadwork vehicles) was struck during the crash.",
  schoolBus = "Derived variable to indicate how many school buses were involved in the crash.",
  seriousInjuryCount = "A count of the number of serious injuries (inj) associated with this crash.",
  slipOrFlood = "Derived variable to indicate how many times landslips, washouts or floods (excluding rivers) were objects struck in the crash.",
  speedLimit = "The speed (spd) limit (lim) in force at the crash site at the time of the crash. May be a number, or 'LSZ' for a limited speed zone.",
  strayAnimal = "Derived variable to indicate how many times a stray animal(s) was struck in the crash. This variable includes wild animals such as pigs, goats, deer, straying farm animals, house pets and birds.",
  streetLight = "The street lighting at the time of the crash. Possible values 'On', 'Off', 'None' or 'Unknown'.",
  suv = "Derived variable to indicate how many SUVs were involved in the crash.",
  taxi = "Derived variable to indicate how many taxis were involved in the crash.",
  tlaId = "The unique identifier for a territorial local authority (TLA). Each crash is assigned a TLA based on where the crash occurred.",
  tlaName = "The name of the territorial local authority (TLA) the crash has been attributed.",
  temporarySpeedLimit = "The temporary (temp) speed (spd) limit (lim) at the crash site if one exists (e.g. for road works).",
  trafficControl = "The traffic control (ctrl) signals at the crash site. Possible values are 'Traffic Signals', 'Stop Sign', 'Give Way Sign', 'Pointsman', 'School Patrol', 'Nil' or 'Unknown'.",
  trafficIsland = "Derived variable to indicate how many times a traffic island, medians (excluding barriers) was struck in the crash.",
  trafficSign = "Derived variable to indicate how many times 'traffic signage' (including traffic signals, their poles, bollards or roadside delineators) was struck in the crash.",
  train = "Derived variable to indicate how many times a train, rolling stock or jiggers was struck in the crash, whether stationary or moving.",
  tree = "Derived variable to indicate how many times trees or other growing items were struck during the crash.",
  truck = "Derived variable to indicate how many trucks were involved in the crash.",
  unknownVehicleType = "Derived variable to indicate how many vehicles were involved in the crash (where the vehicle type is unknown).",
  urban = "A derived variable using the 'spd_lim' variable. Possible values are 'Urban' (urban, spd_lim < 80) or 'Open Road' (open road, spd_lim >=80 or 'LSZ').",
  vanOrUtility = "Derived variable to indicate how many vans or utes were involved in the crash.",
  vehicle = "Derived variable to indicate how many times a stationary attended vehicle was struck in the crash. This includes broken down vehicles, workmen's vehicles, taxis, buses.",
  waterRiver = "Derived variable to indicate how many times a body of water (including rivers, streams, lakes, the sea, tidal flats, canals, watercourses or swamps) was struck in the crash.",
  weatherA = "Indicates weather at the crash time/place. See wthr_b. Values that are possible are 'Fine', 'Mist', 'Light Rain', 'Heavy Rain', 'Snow', 'Unknown'.",
  weatherB = "The weather at the crash time/place. See weather_a. Values 'Frost', 'Strong Wind' or 'Unknown.'"
)

# Create the dataframe
casdata_fd <- data.frame(description = unlist(variable_list), stringsAsFactors = FALSE)

pander(casdata_fd)

rm(variable_list)
```